App/models/exercise.py
from App.database import db
from App.models.category import category
from App.models.muscle import muscle
from App.models.equipment import equipment

exercise_equipment = db.Table(
    'exercise_equipment',
    db.Column('exercise_api_id', db.Integer, db.ForeignKey('exercise.exercise_api_id'), primary_key=True),
    db.Column('equipment_id', db.Integer, db.ForeignKey('equipment.equip_id'), primary_key=True)
)

exercise_muscle = db.Table(
    'exercise_muscle',
    db.Column('exercise_api_id', db.Integer, db.ForeignKey('exercise.exercise_api_id'), primary_key=True),
    db.Column('muscle_id', db.Integer, db.ForeignKey('muscle.musc_id'), primary_key=True)
)

exercise_muscle_2 = db.Table(
    'exercise_muscle_2',
    db.Column('exercise_api_id', db.Integer, db.ForeignKey('exercise.exercise_api_id'), primary_key=True),
    db.Column('muscle_id_2', db.Integer, db.ForeignKey('muscle.musc_id'), primary_key=True)
)



class exercise(db.Model):
    #id = db.Column(db.Integer, primary_key=True)
    exercise_api_id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(120), nullable=False, unique=True)
    description = db.Column(db.String(5000), nullable=False)
   
    
    
    category = db.relationship('category', backref=db.backref('exercise', lazy=True))
    category_id = db.Column(db.Integer, db.ForeignKey('category.cat_id'))
    
  
    
    equipment = db.relationship('equipment', secondary=exercise_equipment, backref=db.backref('exercises', lazy='dynamic'))
    muscle = db.relationship('muscle', secondary=exercise_muscle, backref=db.backref('exercises', lazy='dynamic'))
    muscle_2 = db.relationship('muscle', secondary=exercise_muscle_2, backref=db.backref('exercises_secondary', lazy='dynamic'))

    def __init__(self, exercise_api_id, name, description, category_id):# muscle_id, muscle_id_2):
        self.exercise_api_id = exercise_api_id
        self.name = name
        self.description = description
        #self.cat_name = cat_name
        self.category_id = category_id
        
        

    def __repr__(self):
        return ("exercise: {{self.name}}")

    def get_exercises_for_page(cls, page_number, limit):
        start_point = (page_number - 1) * limit
        return cls.query.offset(start_point).limit(limit).all()

    def search_exercises(self, page):
        matching_exercises = exercise.query
        return matching_exercises.paginate(page=page, per_page=20)

  

App/models/workout.py
from App.database import db
from App.models.workout_exercise import workout_exercise



workout_exercise_final = db.Table(
    'workout_exercise_final',
    db.Column('work_exer_id', db.Integer, db.ForeignKey('workout_exercise.work_exer_id'), primary_key=True),
    db.Column('work_id', db.Integer, db.ForeignKey('workout.work_id'), primary_key=True)
)

class workout(db.Model):

    work_id = db.Column(db.Integer, primary_key = True)
    name = db.Column(db.String(120), nullable=True)
    description = db.Column(db.String(5000), nullable=True)
    # sets = db.Column(db.Integer, nullable=True)
    # reps = db.Column(db.Integer, nullable=True)
    exercise_id = db.Column(db.Integer, nullable=True)
    #user_id = db.Column(db.Integer, nullable=True)


    
    sets_reps = db.relationship('workout_exercise', secondary=workout_exercise_final, backref=db.backref('workouts', lazy='dynamic'))


    def __init__(self, name, description, exercise_id):
        #self.work_id = work_id
        self.name = name
        self.description = description
        # self.sets = sets
        # self.reps = reps
        self.exercise_id = exercise_id
        #self.user_id = user_id
        

App/controllers/exercise.py
from App.models import exercise
from App.models import equipment
from App.models import muscle
#from App.models import category
# from App.models import category
from App.database import db
from flask import request, jsonify

import requests #added requests library to requirements.txt to allow for outbound request calls to api.
import re


def get_all_exercises():
    return exercise.query.all()

def get_exercise(id):
    return exercise.query.filter_by(exercise_api_id=id).first()


def remove_html_tags(text):
    # Code sourced from online to clean the text in api, which contained html tags.
    html_tags_pattern = re.compile(r'<[^>]+>')

    nbsp_pattern = re.compile(r'&nbsp;')
    
    clean_text = re.sub(html_tags_pattern, '', text)
    clean_text = re.sub(nbsp_pattern, '', clean_text)
    return clean_text


def create_exercise(exercise_api_id, name, description):
    new_exercise= exercise(exercise_api_id=exercise_api_id, name=name, description=description) #cat_name=cat_name)
    db.session.add(new_exercise)
    db.session.commit()
    return new_exercise

def get_exercises_from_database(page):
    # Query exercises from the local database model
    
    exercises = exercise.query.paginate(page=page, per_page=20)
    return exercises

def calculate_total_pages(limit):
    # Get total number of exercises in the database
    total_exercises = exercise.query.count()

    # Calculate total pages based on the total number of exercises and the limit per page
    total_pages = (total_exercises + limit - 1) // limit
    return total_pages

def get_all_exercises_api(limit, start_point):
    url = f'https://wger.de/api/v2/exerciseinfo/?limit={limit}&offset={start_point}'
    #the limit=5 means it only renders the 5 at a time
    #the offset=0 means it starts from the 1st one, which is at 0 like an array list
    # can manipulate the url by using variable for the numbers {{}} or ${} whichever one works for this.
    #doing just https://wger.de/api/v2/exercise/ gives the default first 20 exercises, but should use the limit and offset to increment rhough different ones.

    #this works to get api data and works in views and template, but doesnt save data to model and database, finda  way to do this tmr.
    
    response = requests.get(url)
    

    if response.status_code == 200:
        
        exercise_data = response.json().get('results', [])
        total_exercises = response.json().get('count', 0)
        total_pages = (total_exercises + limit - 1) // limit



        for exercise_d in exercise_data:
            #if exercise_d.get('language', {}).get('short_name') == 'en' or exercise_d.get('language', {}).get('id') == 2 or exercise_d.get('language', {}).get('full_name') == 'English':
                name = exercise_d.get('name', '')
                description = exercise_d.get('description', '')
                
                exercise_api_id = exercise_d.get('id')
                category_id = exercise_d.get('category', {}).get('id')
                
                muscles = exercise_d.get('muscles', [])
                muscle_ids = [muscle.get('id') for muscle in muscles]

                muscles2 = exercise_d.get('muscles_secondary', [])
                muscle_ids_2 = [muscle2.get('id') for muscle2 in muscles2]

                # muscle_id = muscle_id[0] if muscle_id else None
                # muscle_id_2 = muscle_id_2[0] if muscle_id_2 else None

                equipment_data = exercise_d.get('equipment', [])
                equipment_ids = [equipment.get('id') for equipment in equipment_data]

                
                
                #print (equipment_ids)


                existing_id_exercise = exercise.query.filter_by(exercise_api_id=exercise_api_id).first()
                existing_name_exercise = exercise.query.filter_by(name=name).first()

                if existing_id_exercise or existing_name_exercise:
                    pass
                else:

                    html_text = description
                    clean_text = remove_html_tags(html_text)
                    
                    n_exercise = exercise(exercise_api_id=exercise_api_id, name=name, description=clean_text, category_id=category_id)#, muscle_id=muscle_id, muscle_id_2=muscle_id_2)

                    db.session.add(n_exercise)

                    for equipment_id in equipment_ids:
                        
                        n_equipment = equipment.query.filter_by(equip_id=equipment_id).first()
                        
                        if n_equipment:
                            n_exercise.equipment.append(n_equipment)
                    
                    for muscle_id in muscle_ids:
                        
                        n_muscle = muscle.query.filter_by(musc_id=muscle_id).first()
                        
                        if n_muscle:
                            n_exercise.muscle.append(n_muscle)

                    for muscle_id_2 in muscle_ids_2:
                        
                        n_muscle_2 = muscle.query.filter_by(musc_id=muscle_id_2).first()
                        
                        if n_muscle_2:
                            n_exercise.muscle_2.append(n_muscle_2)

                            
                    
                    db.session.add(n_exercise)
        db.session.commit()
        #return exercise_data

        
        
        return exercise_data, total_pages
    else:
        return [], 0

def getCategoryExercises(category_id):
    return exercise.query.filter_by(category_id = category_id).all()

App/controllers/user.py
from App.models import User
from App.database import db

def create_user(username, password, country, gender, gym, height, weight):
    newuser = User(username=username, password=password, country=country, gender=gender, gym=gym, height=height, weight=weight)
    db.session.add(newuser)
    db.session.commit()
    return newuser

def get_user_by_username(username):
    return User.query.filter_by(username=username).first()

def get_user(id):
    return User.query.get(id)

def get_all_users():
    return User.query.all()

def get_all_users_json():
    users = User.query.all()
    if not users:
        return []
    users = [user.get_json() for user in users]
    return users

def update_user(id, username):
    user = get_user(id)
    if user:
        user.username = username
        db.session.add(user)
        return db.session.commit()
    return None
    

App/controllers/workout.py
from App.models import workout
from App.models import exercise
from App.models import workout_exercise
from App.models import User
from App.database import db


def get_all_workouts():
    return workout.query.all()


def get_workout(id):
    return workout.query.filter_by(work_id=id).first()


def get_workout_exercises():
    return workout_exercise.query.all()
    #return db.session.query(workout_exercise).filter_by(work_id=1).all()


def create_workout(name, description, exercise_api_id, user_id):
    new_workout= workout(name=name, description=description, exercise_id=exercise_api_id) 

    if new_workout:
        existing_user = User.query.get(user_id)

        if existing_user:
            existing_user.workout.append(new_workout)
            db.session.add(new_workout)
            db.session.commit()
            return new_workout
        else:
            return None
    else:
        return None
 
                        
    # exercise_instance = exercise.query.filter_by(exercise_api_id=exercise_api_id).first()
    

    # if exercise_instance:
    #     new_workout_exercise = workout_exercise(sets=None, reps=None, exercise_id=exercise_instance.exercise_api_id)
    #     new_workout.sets_reps.append(new_workout_exercise)
    #     db.session.add(new_workout)
    #     db.session.commit()
    #     return new_workout
    # else:
    #     return None


def add_exer_to_workout(work_id, exercise_api_id, sets, reps):
    existing_workout= workout.query.get(work_id)
    #existing_workout_exercise = workout_exercise.query.get()

    if existing_workout:
        exercise_instance = exercise.query.filter_by(exercise_api_id=exercise_api_id).first()

        if exercise_instance:
            new_workout_exercise = workout_exercise(sets=sets, reps=reps, exercise_id=exercise_instance.exercise_api_id)
            new_workout_exercise.exercise.append(exercise_instance)
            db.session.add(new_workout_exercise)
            existing_workout.sets_reps.append(new_workout_exercise)
            db.session.add(existing_workout)
            db.session.commit()
            return existing_workout
        else:
            # If the exercise instance doesn't exist, return None
            return None
    else:
        None


def delete_workout(work_id):
    workout = get_workout(work_id)
    if workout:
        db.session.delete(workout)
        db.session.commit()
    else:
        return None


def delete_workout_exercise(work_id, exer_id):
    ex = exercise.query.filter_by(exercise_api_id=exer_id).first()
    existing_workout = workout.query.get(work_id)
    if existing_workout:
        exercise_instance = workout_exercise.query.filter_by(exercise_id=exer_id).first()
        if exercise_instance:
            exercise_instance.exercise.remove(ex)
            db.session.delete(exercise_instance)
            db.session.commit()
        else:
            return None
    else:
        return None

def edit_workout_exercise(work_id, exer_id, sets, reps):
    ex = exercise.query.filter_by(exercise_api_id=exer_id).first()
    existing_workout = workout.query.get(work_id)
    if existing_workout:
        exercise_instance = workout_exercise.query.filter_by(exercise_id=exer_id).first()
        if exercise_instance:
            exercise_instance.sets = sets
            exercise_instance.reps = reps
            db.session.add(exercise_instance)
            db.session.commit()
        else:
            return None
    else:
        return None

def edit_workouts(name, desc, work_id):
    
    existing_workout = workout.query.get(work_id)
    if existing_workout:
        
        
        existing_workout.name = name
        existing_workout.description = desc
        db.session.add(existing_workout)
        db.session.commit()
    else:
        return None

App/views/exercise.py
from flask import Blueprint, render_template, jsonify, request, send_from_directory, flash, redirect, url_for
from flask_jwt_extended import jwt_required, current_user as jwt_current_user

from.index import index_views

import requests

from App.controllers import (get_all_exercises, calculate_total_pages ,get_exercises_from_database ,create_exercise, get_all_exercises_api, get_all_categories, get_all_categories_api, get_all_muscles, get_all_muscles_api, get_all_equipment, get_all_equipment_api, getCategoryExercises)

exercise_views = Blueprint('exercise_views', __name__, template_folder='../templates')

@exercise_views.route('/exercises', methods=['GET'])
@exercise_views.route('/exercises/<int:cat_id>', methods=['GET'])
def get_exercise_page(cat_id = -1):
    
    page = request.args.get('page', 1, type=int)
    limit = 20  # Number of exercises per page
    start_point = (page - 1) * limit
    

    exercises, total_pages = get_all_exercises_api(limit, start_point)

    category = get_all_categories()
    muscles = get_all_muscles()
    equipment = get_all_equipment()
    #exercise_data = get_all_exercises()
    if cat_id == -1:
        exercise_data = get_all_exercises()#THIS SHOULD LOAD ON STARTUP, OR FIND A WAY TO POPULATE MODEL ON STARTUP
    else:
        exercise_data = getCategoryExercises(cat_id)
        if exercise_data:
            pass
        else:
            flash('No Category Found!')

    

    return render_template('exercises.html', exercise_data=exercise_data, category=category, muscles=muscles, equipment=equipment, total_pages=total_pages, page=page, exercises=exercises)

App/views/user.py
from flask import Blueprint, render_template, jsonify, request, send_from_directory, flash, redirect, url_for
from flask_jwt_extended import jwt_required, current_user as jwt_current_user, set_access_cookies

from.index import index_views

from App.controllers import (
    create_user,
    get_all_users,
    get_all_users_json,
    get_user_by_username, 
    jwt_required,
    login
)

user_views = Blueprint('user_views', __name__, template_folder='../templates')


'''
Page/Action Routes
'''  

@user_views.route('/users', methods=['GET'])
@jwt_required()
def get_user_page():
    users = get_all_users()
    return render_template('users.html', users=users, jwt_current_user=jwt_current_user)


@user_views.route('/signup', methods=['GET'])
def get_signup_page():
    return render_template('signup.html')


@user_views.route('/signup', methods=['POST'])
def create_user_action():
    data = request.form
    user = get_user_by_username(data['username'])
    if user:
        flash(f"User {data['username']} already exists!")
        return redirect(url_for('user_views.get_signup_page'))
    flash(f"User {data['username']} created!")
    create_user(data['username'], data['password'], data['country'], data['gender'], data['gym'], data['height'], data['weight'])
    token = login(data['username'], data['password'])
    response = redirect(url_for('workout_views.get_workout_page'))
    set_access_cookies(response, token)
    return response


'''
API Routes
'''

@user_views.route('/api/users', methods=['GET'])
def get_users_action():
    users = get_all_users_json()
    return jsonify(users)


@user_views.route('/api/users', methods=['POST'])
def create_user_endpoint():
    data = request.json
    user = create_user(data['username'], data['password'])
    return jsonify({'message': f"user {user.username} created with id {user.id}"})


@user_views.route('/static/users', methods=['GET'])
def static_user_page():
  return send_from_directory('static', 'static-user.html')

App/templates/401.html
{% extends "layout.html" %}
{% block title %}Not Authorized{% endblock %}
{% block page %}Not Authorized{% endblock %}

{{ super() }}

{% block content %}
<div class="container">
    <div class="row" style="margin-top: 10%;">
        <div class="col s12 m10 offset-m1">
            <div class="card-content">
                <h1>Error: You are not authorized to view this page</h1>
                <p>Create an account or log in with your credentials to gain full access to this website.</p>
                <p>If you wish to browse the website without an account click return to home.</p>
            </div>
            <div class="card-action">
                <a href="/" class="waves-effect waves-light btn">Return to Home</a>
                <a href="/login" class="waves-effect waves-light btn">Sign In</a>
                <a href="/signup" class="waves-effect waves-light btn">Sign Up</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

App/templates/exercises.html
{% extends "layout.html" %}
{% block title %}Exercises{% endblock %}
{% block page %}Exercises{% endblock %}


{% block styles %}

  .card {
    height: 300px;
  }

{% endblock %}

{% block content %}

    <div class="row">
      


      <form method="GET" action="{{ url_for('exercise_views.get_exercise_page') }}">
        <input type="hidden" name="page" value="{{ page }}">
        <a class='dropdown-trigger' href='#' data-target='dropdown1'><i class="medium material-icons">sort</i></a>
        <ul id='dropdown1' class='dropdown-content'>
            {% for cat in category %}
                <li><a href="{{ url_for('exercise_views.get_exercise_page', page=page, cat_id=cat.cat_id) }}">{{ cat.name }}</a></li>
            {% endfor %}
            <li><a href="{{ url_for('exercise_views.get_exercise_page', page=page) }}">No Filter</a></li>
        </ul>
    </form>


      
    </div>
    <div class = "grid-container">
      <div class = "row">
    {%for exer in exercises%}
    
        {%for exercise in exercise_data%}
          {%if exercise.exercise_api_id == exer.id%}
          <div class = "col s6">
            <div class="card">
              <div class="card-content">
                
                
                <span class="card-title activator text-darken-4"><b>{{exercise.name}}</b><i class="material-icons right">more_vert</i></span>
                
                <p><b>Category: </b>{{exercise.category.name}}</p>
                {% if exercise.muscle %}
                  <p><b>Primary Muscles: </b>{%for muscle in exercise.muscle%}{{muscle.name}}  {%endfor%}</p>
                {% endif %}
                {% if exercise.muscle_2 %}
                  <p><b>Secondary Muscles: </b>{%for muscle in exercise.muscle_2%}{{muscle.name}}  {%endfor%}</p>
                {% endif %}
                {% if exercise.equipment %}
                  <p><b>Equipment: </b>{%for equip in exercise.equipment %}{{equip.name}}  {%endfor%}</p>
                {% endif %}
                
                {% if is_authenticated %}
                  <a href="/workouts/{{ exercise.exercise_api_id }}" class="btn-floating btn-large cyan pulse right-bottom" type="submit" style="position: absolute;
                  bottom: 12px;
                  right: 12px;"><i class="material-icons">add</i></a>
                {% else %}
                    <a href="/login" class="btn-floating btn-large cyan pulse right-bottom" style="position: absolute;
                    bottom: 12px;
                    right: 12px;"><i class="material-icons">add</i></a>
                {% endif %}
                

              </div>
              
              <div class="card-reveal" style="background-color: #7a7a7a;">
                <span class="card-title text-darken-4"><b>{{exercise.name}}</b><i class="material-icons right">close</i></span>
                <p>{{exercise.description}}</p>
              </div>
            </div>
          </div>
          {%endif%}
        {%endfor%}
      
    {%endfor%}
  </div>  
</div>

<div class="row">
  <ul class="pagination col s12 center">
      {% if page == 1 %}
          <li class="page-item disabled">
              
          </li>
      {% else %}
          <li class="page-item">
              <a class="page-link" href="{{ url_for('exercise_views.get_exercise_page', page=page-1) }}"><i class="material-icons">chevron_left</i></a>
          </li>
      {% endif %}

      
      
      {% if total_pages <= 9 %}
          {% for page_num in range(1, total_pages + 1) %}
              <li class="page-item {% if page_num == page %}active pulse {% endif %}">
                  <a class="page-link cyan" href="{{ url_for('exercise_views.get_exercise_page', page=page_num) }}">{{ page_num }}</a>
              </li>
          {% endfor %}
      {% else %}
          {% if page < 6 %}
              {% for page_num in range(1, 6) %}
                  <li class="page-item {% if page_num == page %}active pulse {% endif %} cyan">
                      <a class="page-link cyan" href="{{ url_for('exercise_views.get_exercise_page', page=page_num) }}">{{ page_num }}</a>
                  </li>
              {% endfor %}
              <li class="page-item disabled"><a class="page-link" href="#">...</a></li>
              {% for page_num in range(total_pages - 2, total_pages + 1) %}
                  <li class="page-item {% if page_num == page %}active pulse {% endif %}">
                      <a class="page-link cyan" href="{{ url_for('exercise_views.get_exercise_page', page=page_num) }}">{{ page_num }}</a>
                  </li>
              {% endfor %}
          {% elif page > total_pages - 5 %}
              {% for page_num in range(total_pages - 4, total_pages + 1) %}
                  <li class="page-item {% if page_num == page %}active pulse {% endif %} cyan">
                      <a class="page-link cyan" href="{{ url_for('exercise_views.get_exercise_page', page=page_num) }}">{{ page_num }}</a>
                  </li>
              {% endfor %}
              <li class="page-item disabled"><a class="page-link" href="#">...</a></li>
              {% for page_num in range(1, 6) %}
                  <li class="page-item {% if page_num == page %}active pulse {% endif %}">
                      <a class="page-link cyan" href="{{ url_for('exercise_views.get_exercise_page', page=page_num) }}">{{ page_num }}</a>
                  </li>
              {% endfor %}
          {% else %}
              <li class="page-item disabled cyan"><a class="page-link" href="#">...</a></li>
              {% for page_num in range(page - 2, page + 3) %}
                  <li class="page-item {% if page_num == page %}active pulse {% endif %}">
                      <a class="page-link cyan" href="{{ url_for('exercise_views.get_exercise_page', page=page_num) }}">{{ page_num }}</a>
                  </li>
              {% endfor %}
              <li class="page-item disabled"><a class="page-link" href="#">...</a></li>
          {% endif %}
      {% endif %}
      
      {% if page == total_pages %}
          <li class="page-item disabled">
              
          </li>
      {% else %}
          <li class="page-item">
              <a class="page-link" href="{{ url_for('exercise_views.get_exercise_page', page=page+1) }}"><i class="material-icons">chevron_right</i></a>
          </li>
      {% endif %}
  </ul>
</div>

{% endblock%}


  

App/templates/index.html
{% extends "layout.html" %}
{% block title %}ISE Fitness{% endblock %}
{% block page %}ISE Fitness{% endblock %}

{{ super() }}

{% block styles %}
    .container {
        padding: 0px 50px 0px 50px;
    }
{% endblock %}

{% block content %}

    

    <div class="center">
        <h4>Welcome to ISE Fitness</h4>
    </div>
    
    <div class="carousel" style="width: 100%;">
        <a class="carousel-item" href="#one!" style="width: 50%; height:70% "><img src="https://images.unsplash.com/photo-1544033527-b192daee1f5b?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"></a>
        <a class="carousel-item" href="#two!" style="width: 50%; height:70% "><img src="https://images.unsplash.com/photo-1571902943202-507ec2618e8f?q=80&w=1975&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"></a>
        <a class="carousel-item" href="#three!" style="width: 50%; height:70% "><img src="https://images.unsplash.com/photo-1597076545399-91a3ff0e71b3?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"></a>
        <a class="carousel-item" href="#four!" style="width: 50%; height:70% "><img src="https://images.unsplash.com/photo-1526401485004-46910ecc8e51?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MzF8fGd5bSUyMGVxdWlwbWVudHxlbnwwfHwwfHx8MA%3D%3D"></a>
        <a class="carousel-item" href="#five!" style="width: 50%; height:70% "><img src="https://images.unsplash.com/photo-1620188526357-ff08e03da266?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjJ8fGd5bSUyMGVxdWlwbWVudHxlbnwwfHwwfHx8MA%3D%3D"></a>
    </div>

    <br>

    <div class="center">
        <h5>Get ready to take your fitness journey to the next level with our comprehensive workout resources. Whether you're a seasoned gym-goer or just starting out, we've got everything you need to achieve your fitness goals.</h5>
    </div>

    <br>

    <div class="container">
        <p>Explore Our Features:</p>
        <dl>
            <dt>• Extensive Exercise Database</dt>
                <dd>Access thousands of exercises targeting different muscle groups and equipment types.</dd>
            <dt>• Customizable Workouts</dt>
                <dd>Create personalized workout routines tailored to your specific goals and preferences.</dd>
            <dt>• Create Workout Routines</dt>
                <dd>Choose from a wide array of exercises and customize your personal workout routine to fit your goals.</dd>
            <dt>• Track Your Progress</dt>
                <dd>Keep track of all your workouts or specific exercises within the workouts so you never lose sight of the goal.</dd>
            <dt>• Remove</dt>
                <dd>Easily remove exercises that are no longer suitable for you with no hassle.</dd>
        </dl>
    </div>

    <br>

    <div class="center" style="font-size: 20px;">
        <p>Start Your Fitness Journey Today!</p>
        <p>Ready to get started? Sign up now and unlock a world of fitness possibilities. Whether you're aiming to build muscle, lose weight, or improve your overall health, we're here to help you succeed.</p>
    </div>

    <br><br><br>


{% endblock %}

{% block scripts %}
    <script>
        document.addEventListener('DOMContentLoaded', function() {
            var elems = document.querySelectorAll('.carousel');
            var instances = M.Carousel.init(elems, {});
        });
    </script>
{% endblock %}

App/templates/login.html
{% extends "layout.html" %}
{% block title %}Login{% endblock %}
{% block page %}Login{% endblock %}

{{ super() }}

{% block styles %}

    .container{
        padding: 0px 300px 0px 300px;
    }

{% endblock %}

{% block content %}
    
    <br><br>

    <div class="col s12 m7">
        <div class="card horizontal">
            <div class="card-stacked">
                <form method="POST" action="/login" style="align-items: center;">
                    <div class="card-content">
                        <div class="input-field">
                            <input class="white-text" placeholder="username" value="bob" name="username" type="text" class="validate" required>
                            <label for="username">Username</label>
                        </div>
                        <div class="input-field">
                            <input class="white-text" placeholder="password"value="bobpass" name="password" type="password" class="validate" required>
                            <label for="password">Password</label>
                        </div>
                    </div>
                    <div class="card-action">
                        <button type="submit" class="btn waves-effect waves-light cyan">Login</button>
                    </div>

                    <br>

                    <div>
                        <p style="text-align: center;">Not a member? <a href="/signup">Register</a></p>
                    </div>
                </form>
            </div>
        </div>
    </div>

{% endblock %}

App/templates/message.html
{% extends "layout.html" %}
{% block title %}{{title}}{% endblock %}
{% block page %}{{title}}{% endblock %}

{{ super() }}

{% block content %}
<div class="container">
    <div class="row" style="margin-top: 10%;">
        <div class="col s12 m10 offset-m1">
            <p>{{message}}</p>
        </div>
    </div>
</div>
{% endblock %}

App/templates/users.html
{% extends "layout.html" %}
{% block title %}Membership Page {% endblock %}
{% block page %}Membership Page{% endblock %}

{{ super() }}

{% block content %}
<div class="row">
  {% for user in users %}
  <div class="col s12 m6">
    <div class="card">
      <div class="card-content">
        <span class="card-title">Member Details</span>
        <p><b>Member ID:</b> {{user.id}}</p>
        <p><b>Username:</b> {{user.username}}</p>
        <p><b>Country:</b> {{user.country}}</p>
        <p><b>Gender:</b> {{user.gender}}</p>
        <p><b>Current Gym:</b> {{user.gym}}</p>
        <p><b>Weight:</b> {{user.weight}} kg</p>
        <p><b>Height:</b> {{user.height}} cm</p>
      </div>
    </div>
  </div>
  {% endfor %}
</div>
{% endblock %}